###
GET "http://localhost:4004/mysrvdemoService/myfoobar(msg='1@gmail.com')"

###
GET http://localhost:4004/mysrvdemoService/StudentSrv

###
GET http://localhost:4004/mysrvdemoService/StudentSrv(email='1@gmail.com')

###
POST http://localhost:4004/mysrvdemoService/Students
Content-Type: application/json

{
    "email":        "1@gmail.com",
    "first_name":   "first 1",
    "last_name":    "last 1",
    "date_sign_up": "2020-03-23",
    "grade":        "90",
    "country_code": "CA"
}


###
POST http://localhost:4004/mysrvdemoService/Students
Content-Type: application/json

{
    "email":        "2@gmail.com",
    "first_name":   "first 2",
    "last_name":    "last 2",
    "date_sign_up": "2021-03-23",
    "grade":        "85",
    "country_code": "TH"
}


###
POST http://localhost:4004/mysrvdemoService/Students
Content-Type: application/json

{
    "email":        "3@gmail.com",
    "first_name":   "first 3",
    "last_name":    "last 3",
    "date_sign_up": "2021-12-05",
    "grade":        "92",
    "country_code": "TW"
}


###
PUT http://localhost:4004/mysrvdemoService/StudentSrv(email='3@gmail.com')
Content-Type: application/json

{
    "email":        "3@gmail.com",
    "first_name":   "first 33",
    "last_name":    "last 33",
    "date_sign_up": "2021-12-05",
    "grade":        "93",
    "country_code": "TW"
}
